version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      .env
    ports:
      - "5432:5432"

  web-app:
    build: .
    container_name: django
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - db
      - redis
      - worker

  worker:
    build: .
    container_name: celery
    restart: always
    command: celery -A yumezo worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"