# Generated by Django 5.0.6 on 2024-05-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_news_product', models.ImageField(upload_to='images_news_products', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение новостного продукта',
                'verbose_name_plural': 'Изображения новостного продукта',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slider', models.ImageField(upload_to='images_slider', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдеров',
            },
        ),
    ]
