# Generated by Django 5.0.6 on 2024-05-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование категории')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='icons_categories', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование жанра')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование источника')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование товара')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Наименование товара (англ.)')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='icons_products', verbose_name='Изображение продукта')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(help_text='Цена указывается в рублях (руб.)', verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(default=0, help_text='Скидка указывается в процентах (%)', verbose_name='Скидка')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество в наличии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный продукт')),
                ('count_sales', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество продаж')),
                ('rating', models.SmallIntegerField(default=0, editable=False, verbose_name='Средний рейтинг товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Базовый продукт',
                'verbose_name_plural': 'Базовые продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, help_text='Значение задается текстом', max_length=250, null=True, verbose_name='Текстовое значение характеристики')),
                ('value_integer', models.IntegerField(blank=True, help_text='Значение задается целым числом', null=True, verbose_name='Числовое значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
                ('value_genres', models.ManyToManyField(blank=True, help_text='Поле для категорий, в которых есть поле - жанры', null=True, to='catalog.genre', verbose_name='Жанры')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.property', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Сопоставление характеристик продуктов',
                'verbose_name_plural': 'Сопоставление характеристик продуктов',
            },
        ),
    ]
