# Generated by Django 5.0.6 on 2024-06-13 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город / Населенный пункт')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(verbose_name='Дом / корпус')),
                ('apart', models.PositiveSmallIntegerField(verbose_name='Квартира')),
                ('postcode', models.IntegerField(verbose_name='Почтовый индекс')),
                ('create_date', models.DateField(auto_now_add=True, db_index=True)),
                ('total_price', models.PositiveIntegerField(verbose_name='Общая стоимость заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('status', models.CharField(choices=[('CR', 'Создан'), ('DEL', 'В доставке'), ('CONF_DEL', 'Доставлен'), ('REC', 'Получен')], default='CR', verbose_name='Статус заказа')),
                ('carts', models.ManyToManyField(to='catalog.cart', verbose_name='Продукты для заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
