# Generated by Django 5.0.6 on 2024-06-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ пользователя', 'verbose_name_plural': 'Заказы пользователей'},
        ),
    ]
