# Generated by Django 5.0.6 on 2024-06-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_order_carts_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
